(defhydra hydra-launcher (:color purple)
   "Launch"
   ("b" ibuffer "buffer")
   ("d" dired "dired")
   ("f" find-file-at-point "find file")
   ("l" load-file "load file")
   ("p" projectile--find-file "find project file")
   ("s" split-window-vertically "split")
   ("w" evil-write "write")
   ("RET" bookmark-bmenu-list "bookmark-list")
   ("SPC" nil "toggle-hydra"))
(define-key evil-normal-state-map (kbd "SPC") 'hydra-launcher/body)
(define-key dired-mode-map (kbd "SPC") 'hydra-dired/body)


;;(defhydra vdiff-hydra (:color purple)
;;   "Launch"
;;   ("k" vdiff-next-fold "next fold")
;;   ("j" vdiff-prev-fold "prev fold")
;;   ("n" vdiff-next-hunk "next hunk")
;;   ("N" vdiff-prev-hunk "prev hunk")
;;   ("g" vdiff-switch-buffer "switch buffers")
;;   ("f" vdiff-refine-this-hunk "this hunk")
;;   ("F" vdiff-refine-all-hunks "all hunks.")
;;   ("tab" vdiff-toggle-fold "toggle fold.")
;;   ("backtab" vdiff-close-other-folds "toggle other folds.")
;;   ("SPC" nil "toggle-hydra")
;;   ("w" vdiff-save-buffers "save buffers")
;;   ("q" vdiff-hydra/vdiff-quit-and-exit "quit hydra/vdiff"))
